import { StyleSheet } from 'react-native';

import { COLORS } from '../colors';

export default StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'column',
        paddingHorizontal: 15,
        paddingVertical: 15,
        backgroundColor: COLORS.BG,
    },
    headerContainer: {
        marginTop: 30,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 15,
    },
    // backButton: {
    //     position: 'absolute',
    //     left: 0,
    // },
    carouselsContainer: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
    },
    headerText: {
        fontSize: 15,
        fontWeight: 'bold',
        letterSpacing: 0.5,
        color: 'blue',
    },
    // subheaderText: {
    //     fontSize: 18,
    //     fontWeight: 'normal',
    //     letterSpacing: 0.5,
    //     color: COLORS.TEXT,
    //     marginBottom: 5,
    //     textAlign: 'center',
    //     width: '90%',
    // },
    // bottomBar: {
    //     marginTop: 30,
    //     flexDirection: 'row',
    //     justifyContent: 'space-between',
    //     alignItems: 'center',
    //     marginBottom: 15,
    // },
    // button: {
    //     width: 150,
    //     height: 45,
    //     justifyContent: 'center',
    //     alignItems: 'center',
    //     borderWidth: 1,
    //     borderRadius: 12,
    //     borderColor: 'transparent',
    //     marginHorizontal: 5,
    // },
    // buttonText: {
    //     fontSize: 14,
    //     color: 'white',
    //     letterSpacing: 0.5,
    //     textAlign: 'center',
    //     fontWeight: 'bold',
    // },

    // new
    horizontalTabs: {
        // flexDirection: 'row',
        // justifyContent: 'center',
        // alignItems: 'center',
        marginTop: 5,
        marginBottom: 10,
        borderWidth: 1,
        //borderColor: 'red',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        width: '95%',
        height: '6%',
        paddingVertical: 5,
    },
    tabItem: {
        //width: 75,
        // height: 40,
        borderWidth: 1,
        borderRadius: 12,
        borderColor: 'transparent',
        backgroundColor: 'white',
        // justifyContent: 'center',
        // alignItems: 'center',
        marginLeft: 2.5,
        marginRight: 2.5,
    },
    tabItemText: {
        fontSize: 14,
        color: 'black',
        letterSpacing: 0.25,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    optionContainer: {
        width: 95,
        height: 95,
        justifyContent: 'center',
        alignItems: 'center',
    },
    optionSubContainer: {
        width: '87.5%',
        height: '87.5%',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'transparent',
        borderRadius: 12,
        backgroundColor: 'rgba(255,255,255,0.8)',
        flexDirection: 'column',
    },
    optionText: {
        fontSize: 11,
        textAlign: 'center',
    },
    imageContainer: {
        width: '60%',
        height: '60%',
        borderColor: 'transparent',
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    image: {
        width: '95%',
        height: '95%',
    },
});