import { StyleSheet } from 'react-native';

import { COLORS } from '../colors';

export default StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'column',
        paddingHorizontal: 15,
        paddingVertical: 15,
        backgroundColor: COLORS.BG,
    },
    headerContainer: {
        marginTop: 30,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 15,
    },
    carouselsContainer: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
    },
    headerText: {
        fontSize: 15,
        fontWeight: 'bold',
        letterSpacing: 0.5,
        color: 'blue',
    },
    horizontalTabs: {
        marginTop: 5,
        marginBottom: 10,
        borderWidth: 1,
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        width: '95%',
        height: '6%',
        paddingVertical: 5,
    },
    tabItem: {
        borderWidth: 1,
        borderRadius: 12,
        borderColor: 'transparent',
        backgroundColor: 'white',
        marginLeft: 2.5,
        marginRight: 2.5,
    },
    tabItemText: {
        fontSize: 14,
        color: 'black',
        letterSpacing: 0.25,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    optionContainer: {
        width: 95,
        height: 95,
        justifyContent: 'center',
        alignItems: 'center',
    },
    optionSubContainer: {
        width: '87.5%',
        height: '87.5%',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'transparent',
        borderRadius: 12,
        backgroundColor: 'rgb(237,237,237)',
        flexDirection: 'column',
    },
    optionText: {
        fontSize: 11,
        textAlign: 'center',
    },
    imageContainer: {
        width: '60%',
        height: '60%',
        borderColor: 'transparent',
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    image: {
        width: '95%',
        height: '95%',
    },
    popupContainer: {
        flexDirection: 'column',
        backgroundColor: 'transparent',
        width: 150,
        height: 60,
        paddingVertical: 5,
        paddingHorizontal: 5,
        borderWidth: 1,
        borderColor: 'transparent',
        borderRadius: 5,
    },
    popupHeaderText: {
        fontSize: 14,
        fontWeight: 'normal',
        marginBottom: 4,
    },
    popupSubContainer: {
        flexDirection: 'row',
        width: '100%',
        height: '80%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    popupLeftColumn: {
        width: '35%',
        height: '100%',
        flexDirection: 'column',
        justifyContent: 'space-evenly',
        alignItems: 'flex-start',
    },
    popupRightColumn: {
        width: '65%',
        height: '100%',
        flexDirection: 'column',
        justifyContent: 'space-evenly',
        alignItems: 'flex-start',
    },
    popupText1: {
        fontSize: 11,
        fontWeight: 'bold',
        textAlign: 'left',
        marginLeft: 1,
        letterSpacing: 0.5,
    },
    popupText2: {
        fontSize: 11,
        textAlign: 'left',
        letterSpacing: 0.2,
    },
    modalContainer: {
        borderWidth: 1,
        borderColor: 'transparent',
        borderRadius: 12,
        padding: 10,
        backgroundColor: COLORS.BG,
        width: 380,
    },
    modalContentContainer: {
        width: '100%',
        height: '95%',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'center',
        padding: 5,
    },
    modalHeaderContainer: {
        width: '95%',
        marginTop: 10,
        marginBottom: 15,
    },
    modalHeaderText: {
        color: 'black',
        fontSize: 22,
        letterSpacing: 0,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    modalSubHeaderText: {
        fontSize: 18,
        letterSpacing: 1,
        color: 'black',
        marginBottom: 15,
        fontWeight: 'bold',
    },
    modalBodyText: {
        color: 'black',
        fontSize: 14,
        letterSpacing: 0.2,
        lineHeight: 18,
        marginBottom: 15,
    },
    diagramImageContainer: {
        width: '100%',
        height: 260,
        borderColor: 'transparent',
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    diagramImage: {
        width: '95%',
        height: '95%',
    },
    // modal tabs
    modalTabs: {
        borderWidth: 1,
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        marginBottom: -5,
        height: 50,
    },
    modalTabItem: {
        borderWidth: 1,
        borderRadius: 5,
        borderColor: 'transparent',
        backgroundColor: '#E8E6E3',
        marginTop: 10,
    },
    modalTabItemText: {
        fontSize: 12,
        color: 'black',
        letterSpacing: 0,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    modalBottomBar: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
        width: '95%',
        height: 25,
        // borderColor: 'red',
        // borderWidth: 1,
        marginBottom: 30,
    },
    modalBottomBarText: {
        fontSize: 14,
        color: '#4B463E',
        letterSpacing: 0.5,
        fontWeight: 'bold',
        fontStyle: 'italic',
    },
});